site_name: Saad's 2.680 notes
site_url: https://msis.github.io/2680notes/
repo_url: https://github.com/msis/2680notes
edit_uri: tree/main/pages
site_description: Notes for MIT 2.680 students
copyright: |
  Copyright &copy; 2022 <a href="https://github.com/msis/"  target="_blank" rel="noopener">Mohamed Saad Ibn Seddik</a>

docs_dir: 'pages'

theme:
    icon:
      logo: fontawesome/solid/ship
    name: 'material'
    features:
      - content.code.annotate
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      #primary: pink
      #accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      #primary: pink
      #accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.keys
  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - mermaid2:
      arguments:
        # test if its __palette_1 (dark) or __palette_2 (light)
        # for mkdocs-material >=8.0.0
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'
#       for mkdocs-material <8.0.0
#         ^(JSON.parse(window.localStorage.getItem(__prefix('__palette'))).index == 1) ? 'dark' : 'light'

extra_javascript:
    - assets/refresh_on_toggle_theme.js
